### ISSUE TITLE
messages.mo/po missing entry in de_DE

### ISSUE THREAD

**Issue by tachtler** [breisig/phpLDAPadmin#1]
Hi,

after the latest update of phpLDAPamin 1.2.3 on CentOS 7, while using your phpLDAPadmin with PHP 7.x support (Many thanks for that 👍 ), a missing entry in 
`/usr/share/phpldapadmin/locale/de_DE/LC_MESSAGES/messages.mo`
was seen on the web application.

![phpldapadmin_-_anzeige_fehlerhaft](https://user-images.githubusercontent.com/11161944/28768341-8f5bf354-75d7-11e7-90c3-74b20cf5495a.png)

### SOLUTION:
When I override the `/usr/share/phpldapadmin/locale/de_DE/LC_MESSAGES/messages.mo` by the Version distributed with the **phpLDAPadmin Version 1.2.2**, the view was correct, see the screenshot below:

![phpldapadmin_-_anzeige_korrigiert](https://user-images.githubusercontent.com/11161944/28768397-c372fc46-75d7-11e7-8409-50501f21f50b.png)

Please can you update the correct `/usr/share/phpldapadmin/locale/de_DE/LC_MESSAGES/messages.mo` file in **phpLDAPadmin Version 1.2.3** too!

Thank you!
Klaus.

**Comment by breisig** [comment]
Hi Klaus,

I have committed the locale/de_DE/LC_MESSAGES/messages.mo from the phpLDAPadmin 1.2.2 release into master. Please try it out and let me know how it goes.

**Comment by tachtler** [comment]
Hi Boris,

I will test it, in the next view days.

Thank you for committing.
Klaus.

**Comment by breisig** [comment]
@tachtler Any update?

**Comment by tachtler** [comment]
Hi Boris,

it works!

Thank you
Klaus.

**Comment by breisig** [comment]
@tachtler Awesome, thank you for testing.
