### ISSUE TITLE
password_hash_custom issue in php 7.2.7.0?

### ISSUE THREAD

**Issue by filthyjason** [breisig/phpLDAPadmin#3]
Not sure if this is just me, but I cannot create or modify users and I get the following error:

PHP Fatal error:  Uncaught Error: Call to undefined function password_hash_custom() in /usr/share/phpldapa
dmin/lib/PageRender.php:289\nStack trace:\n#0 /usr/share/phpldapadmin/lib/Visitor.php(58): PageRender->getPostAttribute(Object(PasswordAttribute), '0')\n#1 /usr/share/phpldapadmin/lib/PageRe
nder.php(90): Visitor->__call('get', Array)\n#2 /usr/share/phpldapadmin/htdocs/create_confirm.php(19): PageRender->accept()\n#3 /usr/share/phpldapadmin/htdocs/cmd.php(59): include('/usr/shar
e/phpl...')\n#4 {main}\n  thrown in /usr/share/phpldapadmin/lib/PageRender.php on line 289, referer: http://10.1.1.5/phpldapadmin/cmd.php

~Jason

**Comment by breisig** [comment]
@filthyjason Hmmm, It works with earlier versions of php 7.2.x so it should work with php 7.2.7. I will try it out with the latest php 7.2.8

**Comment by filthyjason** [comment]
Any luck testing? is this only affecting me? I have a pretty basic install on my linux box but happy to try something else too.

**Comment by breisig** [comment]
@filthyjason I just installed the latest php 7.2 [7.2.10] on my system and downloaded the latest code and I just tried modifying a user and everything looks good for me.

**Comment by filthyjason** [comment]
I'll look in to my Apache set up, and maybe add SSL on it too. I did a wireshark capture when I tried to add a Generic User Account and saw this coming back:

HTTP/1.0 500 Internal Server Error
Date: Tue, 09 Oct 2018 17:59:13 GMT
Server: Apache/2.4.29 (Ubuntu)
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: private
Pragma: no-cache
Content-Length: 1
Connection: close
Content-Type: text/html; charset="UTF-8"

I can add a Generic DNS Entry just fine, not that I use those, but I just tried it and it works every time.
I've tried multiple browsers on different computers too.

**Comment by filthyjason** [comment]
Ok, resolved. I had not pulled the new "PageRender.php" file when I updated the others :( it was trying to call using the old function name password_hash_custom vs password_hash_pla.
Thanks for the assist and help there, not sure how I missed that file earlier.
