### ISSUE TITLE
running behind nginx has issues

### ISSUE THREAD

**Issue by hasancemcerit** [breisig/phpLDAPadmin#4]
Hi,
I am having the following error when running behind a virtual host on nginx.

Do you have any ideas?
Thanks.

Deprecated: __autoload() is deprecated, use spl_autoload_register() instead in /var/www/phpldapadmin/lib/functions.php on line 54

Fatal error: Cannot redeclare password_hash() in /var/www/phpldapadmin/lib/functions.php on line 2236

**Comment by idanoo** [comment]
Hmm, I had that issue using the official repo (Not this fork). Since moving to this one I don't have that issue anymore. 

This repo explicitly changed password_hash() so that wouldn't happen.

**Comment by breisig** [comment]
This only effects the official repo and not my fork.
