### ISSUE TITLE
Tree in left panel - cannot roll down with PHP 7.3

### ISSUE THREAD

**Issue by Mieszko01** [breisig/phpLDAPadmin#7]
My system:
Debian 9 with PHP 7.3 from Buster.

```
php -v
PHP 7.3.0-2 (cli) (built: Dec 17 2018 09:51:53) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.0-dev, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.0-2, Copyright (c) 1999-2018, by Zend Technologies
```

On the left side of position: [+] dc=mycompany,dc=local should be icon with "+" - but is none picture.  I can click on the missing icon - the icon is changed to spinning gif, none request from webbrowser is send to server.

In logs from Apache:

`[Tue Jan 22 13:52:54.665745 2019] [php7:warn] [pid 13617] [client 10.0.0.187:56118] PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home/www_phpLDAPadmin_php7_breisig/lib/QueryRender.php on line 324, referer: http://10.0.0.102/phpldapadmin_breisig/htdocs/cmd.php?server_id=1&redirect=true`

Based on the description from: [https://wiki.php.net/rfc/continue_on_switch_deprecation](https://wiki.php.net/rfc/continue_on_switch_deprecation) I tried changing this "continue" to "break" or "continue 2" but this gives nothing.

**Comment by sharbich** [comment]
Hello,

this does not work with PHP version 7.3. You have to downgrade to PHP Version 7.2. In Apache disable PHP version 7.3 and activate version 7.2.
`a2dismod php7.3`
`a2enmod php7.2`
`systemctl restart apache2.service`

Greetings from Stefan Harbich

**Comment by Mieszko01** [comment]
THX.

**Comment by obriensystems** [comment]
getting this during a search function using 7.3 - will try the downgrade.
https://github.com/obrienlabs/phpldapadmin-for-xampp/commits/master
